config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :actors do
    resources :comments, module: :actors
  end
  resources :films do
    resource :comments, module: :films
  end

  root to: "films#index"
end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id          :integer          not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image_id    :string
#
class Actor < ApplicationRecord
  has_many :comments, as: :commentable
  attachment :image
end

app/models/actor_film.rb
# == Schema Information
#
# Table name: actor_films
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  actor_id   :integer
#  film_id    :integer
#
class ActorFilm < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text
#  commentable_type :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_id   :integer
#  user_id          :integer
#
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id          :integer          not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image_id    :string
#
class Film < ApplicationRecord
  has_many :comments, as: :commentable
  attachment :image
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default("0"), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/actors/comments_controller.rb
class Actors::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Actor.find(params[:actor_id])
    end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:name, :description, :image, :image_cache_id, :remove_image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user
    @comment.save
    redirect_to @commentable, notice: "Your comment was successfully posted."
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/films/comments_controller.rb
class Films::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Film.find(params[:film_id])
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:title, :description, :image, :image_cache_id, :remove_image)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 3 %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.attachment_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <% if @actor.image_id? %>
      <%= image_tag attachment_url(@actor, :image, :fill, 100, 100), class: "img-rounded" %>

      <%= f.check_box :remove_image %>
      <%= f.label :remove_image %>
    <% end %>
  </div>
  <div class="actions mt-10">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= link_to image_tag(attachment_url(actor, :image, :fill, 150, 150)), actor %></td>
        <td><%= link_to actor.name, actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %> | <%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @actor.name %></h1>
<div class="row">
  <div class="col-md-4">
    <%= image_tag attachment_url(@actor, :image, :fill, 300, 300) if @actor.image %>
  </div>
  <p><%= simple_format @actor.description %></p>

  <%= link_to 'Edit', edit_actor_path(@actor) %> |
  <%= link_to 'Back', actors_path %>
</div>

<%= render partial: "comments/comments", locals: {commentable: @actor} %>
<%= render partial: "comments/form", locals: {commentable: @actor} %>

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% commentable.comments.each do |comment| %>
  <div class="well">
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control", placeholder: "Add a comment" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 3 %>
  </div>
  <div class="form-group" id="image_attachment_upload">
    <%= f.label :image %>
    <%= f.attachment_field :image, direct: true %>
  </div>
  <div class="row">
    <div class="col-md-3">

      <div id="image"></div>

      <% if @film.image_id? %>
        <%= image_tag attachment_url(@film, :image, :fill, 100, 100), class: "img-rounded" %>

        <%= f.check_box :remove_image %>
        <%= f.label :remove_image %>
      <% end %>
    </div>
    <div id="image"></div>
  </div>

  <div class="actions mt-10">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Films</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image </th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= link_to image_tag(attachment_url(film, :image, :limit, 250, 150)), film if film.image %></td>
        <td><%= link_to film.title, film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %> | <%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice" class="bg-info"><%= notice %></p>

<h1><%= @film.title %></h1>
<div class="row">
  <div class="col-md-4">
    <%= image_tag attachment_url(@film, :image, :limit, 300, 500) if @film.image %>
  </div>
  <p><%= simple_format @film.description %></p>

  <%= link_to 'Edit', edit_film_path(@film) %> |
  <%= link_to 'Back', films_path %>
</div>

<%= render partial: "comments/comments", locals: {commentable: @film} %>
<%= render partial: "comments/form", locals: {commentable: @film} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolymorphicComments36</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Movie Database</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Films", films_path %></li>
            <li><%= link_to "Actors", actors_path %></li>
          </ul>

          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <%= yield %>
    </div>
    <div class="panel-footer panel-footer-main text-right">Panel footer</div>
  </body>
</html>